services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15
    container_name: tg_bot_postgres
    env_file:
      - .env
    ports:
      - "5433:5432"  # Используем порт 5433 для избежания конфликтов
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tg_bot_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tg_bot_user -d tg_bot_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Telegram Bot
  bot:
    image: greenteeea/delta:latest
    container_name: kvt-bot
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "5000:5000"  # Webhook сервер для CryptoPay / YooKassa
    # environment variables are in .env
    # используем настройки образа, без переопределения пользователя/директории
    networks:
      - tg_bot_network
    restart: unless-stopped
    # используем CMD/ENTRYPOINT образа

volumes:
  postgres_data:

networks:
  tg_bot_network:
    driver: bridge